// KNM Flashcards dataset
// Structure: { id, term, definition, category, subcategory }

const RAW_SECTIONS = [
  {
    category: "Wonen",
    subcategory: "Een huis regelen",
    items: [
      ["Sociale huur", "Social rent"],
      ["Woningbouwvereniging", "Housing association where you can register if you are looking for a rental home"],
      ["Woningcorporatie", "Housing association where you can register if you are looking for a rental home"],
      ["Wachtlijst", "Waiting list"],
      ["Urgentieverklaring", "Declaration of urgency (in case you are waiting for a house in social rent)"],
      ["Vrije sector", "Rental houses that are not social rent"],
      ["Huisbaas", "Landlord"],
      ["Makelaar", "Realtor"],
      ["Huurcontract", "Rental contract"],
      ["Huurder", "Tenant"],
      ["Servicekosten", "Service costs"],
      ["Opzegtermijn", "Notice period"],
      ["Belastingdienst", "Tax authority"],
      ["Huurtoeslag", "Rent allowance; money people with low income can get back from the tax authority"],
      ["Hypotheek", "Mortgage"],
      ["Rente", "Interest"],
      ["Belastingaangifte", "Tax return"],
      ["Hypotheekrenteaftrek", "Interest deduction; deducting the interest you pay on your mortgage from your income when doing your tax return"],
      ["Notaris", "Notary"],
      ["Verzekeringen", "Insurances"],
      ["Aansprakelijkheidsverzekering", "Liability insurance"],
      ["Inboedelverzekering", "Home insurance"],
    ],
  },
  {
    category: "Wonen",
    subcategory: "Energie en communicatie",
    items: [
      ["Energiebedrijf", "Energy company"],
      ["Meterstand", "Meter reading (of gas, electricity, water)"],
      ["Energierekening", "Energy bill"],
      ["Termijnbedrag", "Monthly amount that needs to be paid for energy in your house"],
      ["Jaarrekening", "Annual bill for energy in your house"],
      ["Duurzame energie", "Sustainable energy"],
      ["Nederlandse publieke omroep (NPO)", "Dutch public broadcaster"],
      ["Overheid", "Government"],
      ["Abonnement", "Subscription"],
      ["Storing", "Technical issue (mostly concerning electricity)"],
    ],
  },
  {
    category: "Wonen",
    subcategory: "Onderhoud en woonomgeving",
    items: [
      ["Glasbak", "Glass container"],
      ["Papierbak", "Paper container"],
      ["Groene container", "Container for vegetables, fruit and garden waste"],
      ["Groente, fruit, tuin (GFT) container", "Container for vegetables, fruit and garden waste"],
      ["Plasticbak", "Plastic container"],
      ["Chemisch afval", "Chemical waste"],
      ["Klein chemisch afval", "Waste disposal for all types of small chemical waste (batteries, paint etc.)"],
      ["Belasting", "Tax"],
      ["Ontheffing", "Exemption"],
    ],
  },

  {
    category: "Werk en inkomen",
    subcategory: "Snel en efficiënt werk zoeken",
    items: [
      ["Vacature", "Job application"],
      ["UWV WERKbedrijf", "Government initiative that helps unemployed people (with finding a job and receiving an allowance)"],
      ["Solliciteren", "Applying for a job"],
      ["Uitzendbureau", "Employment agency"],
      ["Tijdelijk werk", "Temporary work"],
      ["Bepaalde tijd", "For a determined period of time"],
      ["Onbepaalde tijd", "For an undetermined period of time"],
      ["Internationale diplomawaardering (IDW)", "International diploma evaluation (to see what a foreign diploma is worth in the Netherlands)"],
      ["Diploma waarderen", "Evaluating a diploma (to see what a foreign diploma is worth in the Netherlands)"],
      ["Dienst uitvoering onderwijs (DUO)", "Governmental organisation responsible for education and financing of people’s education"],
      ["Regionaal Opleidingscentrum (ROC)", "Regional education centers that exist all over the Netherlands. Many people are educated here for a certain profession"],
      ["Re-integratiebedrijf", "Re-integration company; helps people who haven’t had a job for a longer period of time get a job"],
      ["Bijscholing / Nascholing", "Additional training/schooling"],
      ["EVC", "Organization responsible for evaluation and recognition of prior working experience"],
      ["Vrijwilligerswerk", "Voluntary work"],
      ["Sollicitatieplicht", "Job application duty"],
      ["WW-uitkering", "Unemployment allowance"],
      ["WIA-uitkering", "Disability allowance"],
      ["AOW", "State pension"],
      ["Bijstand", "Income support"],
    ],
  },
  {
    category: "Werk en inkomen",
    subcategory: "Werken bij een bedrijf / organisatie",
    items: [
      ["Werkgevers", "Employers"],
      ["Werknemers", "Employees"],
      ["Arbeidscontract", "Employment contract"],
      ["Proeftijd", "Probation period when starting a new job"],
      ["Vast contract", "Fixed contract"],
      ["Tijdelijk contract", "Temporary contract"],
      ["Contract via uitzendbureau", "Contract through employment agency"],
      ["Veiligheid", "Safety"],
      ["Gezondheid", "Health"],
      ["Bedrijfsarts / Arboarts", "Health and safety officer in a company / organisation"],
      ["Re-integratieplan", "Re-integration plan"],
      ["Arbo-wet", "Working conditions act"],
      ["Ondernemingsraad (OR)", "Works council"],
      ["Medezeggenschapsraad (MR)", "Participation council"],
      ["Personeelsvereniging (PV)", "Staff association"],
      ["Lastenverdeling", "Burden sharing (regarding taxes; the higher your income the more tax you pay)"],
      ["Belasting", "Tax"],
      ["Belastingdienst", "Tax authority"],
      ["AOW", "State pension"],
      ["WW", "Unemployment allowance"],
      ["Netto salaris", "Net salary"],
      ["Bruto salaris", "Gross salary"],
      ["Loonstrookje", "Payslip"],
      ["Jaaropgave", "Overview of income in past year"],
      ["Belastingaangifte", "Tax return"],
      ["Collectieve arbeidsovereenkomst (CAO)", "Collective labour agreement"],
      ["Vakbond", "Trade/labour unions"],
    ],
  },
  {
    category: "Werk en inkomen",
    subcategory: "Eigen bedrijf",
    items: [
      ["Kamer van Koophandel", "Chamber of commerce"],
      ["KvK-nummer", "Chamber of commerce number"],
      ["Ondernemersplan", "Business plan (you must show this to the bank if you want to get a loan)"],
    ],
  },

  {
    category: "Interactie, normen en waarden",
    subcategory: "Interactie in Nederland",
    items: [
      ["Gefeliciteerd", "Congratulations"],
      ["Gecondoleerd", "Condolences"],
      ["Wachtkamer", "Waiting room"],
      ["Openbaar vervoer", "Public transport"],
      ["Vervoersbewijs", "Transportation ticket"],
      ["Stiltecoupés", "Silent compartments in train"],
      ["Gemeente", "Municipality"],
      ["Uitvoeringsinstituut Werknemersverzekeringen (UWV)", "Government institution responsible for unemployment allowance (WW), disability allowance (WIA) etc."],
      ["Samenlevingscontract", "Cohabitation contract"],
      ["Gezin", "Family/household (normally two parents and one or more children)"],
      ["Eenoudergezin", "Single parent family"],
    ],
  },
  {
    category: "Interactie, normen en waarden",
    subcategory: "Nederlandse waarden en normen",
    items: [
      ["Waarden", "Values (things people in the Netherlands find important)"],
      ["Normen", "Rules resulting from values"],
      ["Vrijheid van meningsuiting", "Freedom of expression"],
      ["Grondwet", "Constitution"],
      ["Geweld", "Violence"],
      ["Huiselijk geweld", "Domestic violence"],
    ],
  },
  {
    category: "Interactie, normen en waarden",
    subcategory: "Een sociaal netwerk opbouwen",
    items: [
      ["Sociaal netwerk", "Social network"],
      ["Buurt", "Neighborhood"],
      ["Vereniging", "Club; for example a football club or dancing club"],
      ["Buurthuis", "Community center"],
    ],
  },
  {
    category: "Interactie, normen en waarden",
    subcategory: "Feest- en familiedagen",
    items: [
      ["Kerst", "Christmas"],
      ["Pasen", "Easter"],
      ["Sinterklaas", "A feast on the 5th of December. Children receive presents from Sinterklaas. Adults also celebrate Sinterklaas and give each other presents"],
      ["Schoentje zetten", "Leaving your shoe; children leave their shoe for Sinterklaas before going to bed. The next morning Sinterklaas has left sweets and maybe a small present in the shoe"],
      ["Koningsdag", "Kingsday; Dutch celebrate the birthday of king Willem-Alexander"],
      ["Bevrijdingsdag", "On the 5th of May Dutch celebrate the liberation from Germany in the second world war in 1945"],
      ["Pinksteren", "Pentecost"],
      ["Hemelvaart", "Ascension Day"],
      ["Oud en nieuw", "New Year’s Eve"],
      ["Trakteren", "Giving a treat; Dutch give a treat at school or at work when it’s their birthday"],
      ["Geboorte", "Childbirth"],
      ["Kraamvisite", "Baby shower"],
      ["Beschuit met muisjes", "Biscuits with sprinkles; when a child is born people eat biscuits with sprinkles at the baby shower. Pink sprinkles for girls, blue sprinkles for boys"],
      ["Bruiloft", "Wedding celebration"],
      ["Trouwdag", "Wedding Day"],
      ["Receptie", "Reception after the wedding ceremony; people can congratulate the couple"],
      ["Geslaagd", "Graduated"],
      ["Schooltas aan de vlaggenstok", "School bag in the flagpole; Dutch tradition for when you have graduated high school"],
      ["‘Gefeliciteerd’", "Congratulations"],
      ["‘Gecondoleerd’", "Condolences"],
    ],
  },

  {
    category: "Onderwijs en opvoeding",
    subcategory: "Zorgen voor jonge kinderen",
    items: [
      ["Zwanger", "Pregnant"],
      ["Verloskundige", "Midwife"],
      ["Bevalling", "Child birth"],
      ["Thuiszorg", "Home care"],
      ["Consultatiebureau", "Consultation agency; for children from 0-4 years old"],
      ["Kinderdagverblijf", "Day care"],
      ["Oppas", "Babysitter"],
      ["Gastouderopvang", "Host parent care"],
      ["Gastouder", "Host parent"],
    ],
  },
  {
    category: "Onderwijs en opvoeding",
    subcategory: "Het Nederlandse schoolsysteem",
    items: [
      ["Peuterspeelzaal", "Playroom (for children from 2-4 years old)"],
      ["Voorschool", "Pre-school (for children from 2-4 years old who are behind in their development or don’t speak Dutch at home)"],
      ["Basisschool", "Elementary school"],
      ["Buitenschoolse opvang", "After school care; for elementary school children whose parents cannot take care of them after school"],
      ["Middelbare school / voortgezet onderwijs", "High school"],
      ["VWO", "High school for children who can study very well (6 years)"],
      ["HAVO", "High school for children who can study well (5 years)"],
      ["VMBO", "High school for children who cannot study very well (4 years)"],
      ["De universiteit", "Highest level after high school education"],
      ["HBO", "Second highest level after high school education"],
      ["MBO", "Lowest level after high school education"],
      ["Leerplicht", "Mandatory schooling"],
      ["Boete", "Fine"],
      ["Vrijheid van onderwijs", "Freedom of education; parents can choose any school or start one"],
      ["Openbare school", "Public school"],
    ],
  },
  {
    category: "Onderwijs en opvoeding",
    subcategory: "Kosten voor kinderen en studiefinanciering",
    items: [
      ["Kinderopvang", "Childcare"],
      ["Kinderopvangtoeslag", "Childcare allowance"],
      ["Kinderbijslag", "Child support"],
      ["Sociale Verzekeringsbank (SVB)", "Social security bank"],
      ["Ouderbijdrage", "Parental contribution"],
      ["Lesgeld", "Tuition"],
      ["Dienst Uitvoering Onderwijs (DUO)", "Government organisation for education financing"],
      ["Studiefinanciering", "Government study financing"],
    ],
  },
  {
    category: "Onderwijs en opvoeding",
    subcategory: "Verantwoordelijkheid voor kinderen",
    items: [
      ["Volwassen", "Adults"],
      ["Huisarts", "General practitioner"],
      ["Bureau jeugdzorg", "Youth Care Office"],
      ["De geestelijke gezondheidszorg (ggz)", "Mental health institution"],
      ["Ouderavonden", "Parents evenings"],
      ["10-minutengesprekken", "10-minute teacher meetings about your child"],
      ["Rapportavonden", "Report card evenings"],
      ["Vrijwilliger", "Volunteer"],
    ],
  },

  {
    category: "Gezondheid",
    subcategory: "De huisarts",
    items: [
      ["Kennismakingsgesprek", "Intake with GP"],
      ["Telefonisch spreekuur", "Telephone consultation hour"],
      ["Huisbezoek", "Home visit"],
      ["Tolkencentrum", "Translator center"],
      ["Beroepsgeheim", "Professional secrecy"],
      ["Huisartsenpost", "GP center for out-of-hours care"],
      ["Recept", "Prescription"],
      ["Apotheek", "Pharmacy"],
      ["Drogist", "Drugstore"],
      ["Zorgverzekering", "Health insurance"],
      ["Eigen bijdrage", "Own contribution"],
      ["Controle", "Check-up"],
      ["Tandarts", "Dentist"],
      ["Wachtlijst", "Waiting list"],
      ["Tandartsverzekering", "Dental insurance"],
      ["Basisverzekering", "Basic mandatory insurance"],
    ],
  },
  {
    category: "Gezondheid",
    subcategory: "Ziekenhuis en specialist",
    items: [
      ["Verwijsbrief", "Referral letter"],
      ["Polikliniek", "Hospital department"],
      ["Patiëntenpas", "Patient card"],
      ["Verzekeringsbewijs", "Insurance certificate"],
      ["Identiteitsbewijs", "ID"],
      ["Wachtkamer", "Waiting room"],
      ["Opname", "Hospitalisation"],
      ["Maatschappelijk werk", "Social services"],
      ["Geestelijke gezondheidszorg (GGZ)", "Mental healthcare"],
      ["Gemeentelijke gezondheidsdienst (GGD)", "Municipal health service"],
      ["Seksueel Overdraagbare Aandoening (SOA)", "STD"],
      ["Huisartsenpost", "GP center for out-of-hours care"],
      ["Verzekeringsnummer", "Insurance number"],
      ["112", "Emergency number"],
      ["Spoedeisende hulp", "Emergency room"],
    ],
  },
  {
    category: "Gezondheid",
    subcategory: "Zwangerschap en bevalling",
    items: [
      ["Verloskundige", "Midwife"],
      ["Kraamhulp", "Maternity help"],
      ["Consultatiebureau", "Child consultation agency"],
      ["Groeiboekje", "Child growth book"],
    ],
  },
  {
    category: "Gezondheid",
    subcategory: "Ouderen en gehandicapten",
    items: [
      ["Thuiszorg", "Home care"],
      ["Mantelzorg", "Informal care by family/friends"],
      ["Verzorgingshuis/Verpleeghuis", "Nursing home"],
    ],
  },
  {
    category: "Gezondheid",
    subcategory: "Zorgkosten en zorgverzekering",
    items: [
      ["Zorgverzekering", "Health insurance"],
      ["Basisverzekering", "Basic insurance"],
      ["Gezondheidszorg", "Health care"],
      ["Premie", "Premium"],
      ["Aanvullende verzekering", "Additional insurance"],
      ["Tandartsverzekering", "Dental insurance"],
      ["Eigen risico", "Own risk amount"],
      ["Eigen bijdrage", "Own contribution"],
      ["Formulier teruggave", "Insurance refund form"],
      ["Declareren", "To claim costs from insurer"],
      ["Zorgtoeslag", "Health care allowance"],
    ],
  },

  {
    category: "Instanties",
    subcategory: "De gemeente",
    items: [
      ["Gemeente", "Municipality"],
      ["Gemeentelijke Basisadministratie (GBA)", "Municipal register"],
      ["Rijbewijs", "Driver’s licence"],
      ["Uittrekstel Gemeentelijk Basisadministratie", "Official document from municipal admin"],
      ["Vergunning", "Licence/permit"],
      ["Verblijfsvergunning", "Residence permit"],
      ["Tijdelijke verblijfvergunning", "Temporary residence permit"],
      ["Bepaalde tijd", "Determined period"],
      ["Permanente verblijfsvergunning", "Permanent residence permit"],
      ["Onbepaalde tijd", "Undetermined period"],
      ["Naturalisatie", "Naturalisation"],
    ],
  },
  {
    category: "Instanties",
    subcategory: "De politie",
    items: [
      ["Identificatieplicht", "Obligation to identify"],
      ["Rijbewijs", "Driver’s licence"],
      ["Openbare orde", "Public order"],
      ["Aangifte doen", "File a report"],
      ["112", "Emergency number"],
    ],
  },
  {
    category: "Instanties",
    subcategory: "Belastingaangifte en toeslagen",
    items: [
      ["Burgerservicenummer (BSN)", "Social Security Number"],
      ["DigiD code", "Online government services code"],
      ["Belastingkantoor", "Local tax office"],
      ["Bezwaar", "Objection to government decision"],
      ["Kwijtschelding", "Payment exemption"],
      ["In termijnen te betalen", "Payment in instalments"],
      ["Toeslagen", "Allowances"],
      ["Huurtoeslag", "Rent allowance"],
      ["Zorgtoeslag", "Health care allowance"],
      ["Kinderopvangtoeslag", "Childcare allowance"],
    ],
  },
  {
    category: "Instanties",
    subcategory: "Juridische en sociale hulp",
    items: [
      ["Bezwaar", "Objection"],
      ["Anti-discriminatiebureau", "Anti-discrimination office"],
      ["Juridisch Loket", "Legal advice office"],
      ["Advocatenkantoor", "Law firm"],
    ],
  },
  {
    category: "Instanties",
    subcategory: "Bank",
    items: [
      ["Bankrekening", "Bank account"],
      ["Bankpas", "Bank card"],
      ["Automatisch betalen via een machtiging", "Authorised automatic payment"],
      ["Internetbankieren", "Online banking"],
    ],
  },
  {
    category: "Instanties",
    subcategory: "Verzekeringen",
    items: [
      ["Zorgverzekering", "Health insurance"],
      ["Autoverzekering", "Car insurance"],
      ["Premie", "Premium"],
      ["Aansprakelijkheidsverzekering", "Liability insurance"],
      ["Brandverzekering", "Fire insurance"],
      ["Reisverzekering", "Travel insurance"],
      ["Schade", "Damage"],
    ],
  },

  {
    category: "Politiek",
    subcategory: "Wet- en regelgeving",
    items: [
      ["Rechtstaat", "Constitutional state"],
      ["De wet", "The law"],
      ["Grondwet", "Constitution"],
      ["Vrijheid van meningsuiting", "Freedom of expression"],
      ["Vrijheid van godsdienst", "Freedom of religion"],
      ["Vrijheid van onderwijs", "Freedom of education"],
      ["Scheiding tussen de wet en religie", "Separation of law and religion"],
      ["Boete", "Fine"],
      ["Gevangenis", "Prison"],
      ["Slachtofferhulp Nederland", "Victim support Netherlands"],
      ["De scheiding van de machten", "Separation of powers"],
      ["Uitvoerende macht", "Executive power"],
      ["Wetgevende macht", "Legislative power"],
      ["Rechterlijke macht", "Judicial power"],
      ["Regering", "Government"],
      ["Koning", "King"],
      ["Minister-president", "Prime minister"],
      ["Ministers", "Ministers"],
      ["De Eerste Kamer", "Senate"],
      ["De Tweede Kamer", "House of Representatives"],
      ["Parlement", "Parliament"],
      ["Rechters", "Judges"],
    ],
  },
  {
    category: "Politiek",
    subcategory: "Het bestuur van Nederland",
    items: [
      ["Democratie", "Democracy"],
      ["Koninkrijk", "Kingdom"],
      ["Rechtstaat", "Constitutional state"],
      ["Grondwet", "Constitution"],
      ["Verkiezingen", "Elections"],
      ["Kiesrecht", "Right to vote"],
      ["Actief kiesrecht", "Active voting right"],
      ["Passief kiesrecht", "Passive voting right"],
      ["Landelijke bestuur", "National government"],
      ["Tweede Kamer verkiezingen", "House of Representatives elections"],
      ["De provincies", "Provinces"],
      ["De gemeentes", "Municipalities"],
      ["De waterschappen", "Water authorities"],
      ["De Europese Unie", "European Union"],
      ["Referendum", "Referendum"],
      ["Minister-president", "Prime minister"],
      ["Staatssecretaris", "Secretary of state"],
      ["Het kabinet", "Cabinet"],
      ["Het parlement", "Parliament"],
      ["Commissaris van de koning", "King’s Commissioner"],
      ["Planologie", "Spatial planning"],
      ["De Gemeenteraad", "Municipal council"],
      ["De burgemeester", "Mayor"],
      ["Deelgemeenten", "Sub-municipalities"],
      ["Deelgemeenteraad", "Sub-municipal council"],
      ["Europese Commissie", "European Commission"],
      ["Troonrede", "Speech from the throne"],
      ["Rechts", "Right-wing"],
      ["Links", "Left-wing"],
      ["Progressief", "Progressive"],
      ["Conservatief", "Conservative"],
      ["Lijsttrekker", "Party leader during elections"],
      ["Stembureau", "Polling station"],
      ["Stembiljet", "Ballot"],
      ["Meerderheid", "Majority"],
      ["Meerderheidspartijen", "Majority parties"],
      ["Coalitie", "Coalition"],
      ["Oppositie", "Opposition"],
    ],
  },

  {
    category: "Geschiedenis en geografie",
    subcategory: "Geschiedenis van Nederland",
    items: [
      ["De Tachtigjarige Oorlog", "80-year war with Spain (1568–1648)"],
      ["Koning Filips II", "King of Spain during much of that war"],
      ["Protestanten", "Protestants opposing Catholic rule"],
      ["Willem van Oranje", "Leader of the revolt against Spain"],
      ["‘Het Wilhelmus’", "Dutch national anthem"],
      ["Republiek der zeven verenigde Nederlanden", "Dutch Republic after independence in 1648"],
      ["De gouden eeuw", "Golden Age (1600–1700)"],
      ["Verenigde Oost-Indische Compagnie (VOC)", "Major Dutch trading company"],
      ["De industriële revolutie", "Industrial Revolution (1800–1900)"],
      ["Socialisten", "Socialists fighting for workers’ rights"],
      ["Koningin Wilhelmina", "Queen during WWII, fled to England"],
      ["Verzet", "The resistance during WWII"],
      ["5 mei 1945", "Liberation Day"],
      ["Grote overstroming", "1953 flood in Zeeland and Zuid-Holland"],
      ["Het Deltaplan", "Water protection plan after the flood"],
      ["Deltawerken", "Delta Works project"],
      ["Ontkerkelijking", "Secularisation (1960–1970)"],
      ["Gastarbeiders", "Migrant workers"],
    ],
  },
  {
    category: "Geschiedenis en geografie",
    subcategory: "Geografie en de mensen van Nederland",
    items: [
      ["Amsterdam", "Capital"],
      ["Schiphol", "Main airport"],
      ["Rotterdam", "Second city, major harbour"],
      ["Den Haag", "Political capital"],
      ["Utrecht", "Fourth city"],
      ["De Randstad", "Urban area (Amsterdam, Rotterdam, Den Haag, Utrecht)"],
      ["De Veluwe", "Nature area in Gelderland"],
      ["De Waddeneilanden", "Northern islands"],
    ],
  },
];

function buildCards() {
  const cards = [];
  let idCounter = 1;
  for (const sec of RAW_SECTIONS) {
    for (const [term, definition] of sec.items) {
      cards.push({
        id: String(idCounter++),
        term,
        definition,
        category: sec.category,
        subcategory: sec.subcategory,
      });
    }
  }
  return cards;
}

const ALL_CARDS = buildCards();


